#!/usr/bin/env node
/**
 * Reads repo-root .env and writes src/env.generated.ts for the React Native app.
 * Run automatically via prestart / preios / preandroid.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(appRoot, '..');
const envPath = path.join(repoRoot, '.env');
const outPath = path.join(appRoot, 'src', 'env.generated.ts');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const vars = {};
  for (const line of fs.readFileSync(filePath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

function tsString(value) {
  return JSON.stringify(value);
}

const env = parseEnvFile(envPath);
const target = env.DONNA_VOICE_TARGET === 'production' ? 'production' : 'local';
const wsOverride = env.DONNA_VOICE_WS_URL?.trim() || null;
const hostOverride = env.DONNA_VOICE_HOST_OVERRIDE?.trim() || null;

const contents = `// AUTO-GENERATED by scripts/sync-env.mjs — do not edit
// Re-run: npm start (or: node scripts/sync-env.mjs)

export const ENV_VOICE_TARGET = ${tsString(target)} as 'local' | 'production';
export const ENV_VOICE_WS_URL_OVERRIDE = ${
  wsOverride ? tsString(wsOverride) : 'null'
} as string | null;
export const ENV_VOICE_HOST_OVERRIDE = ${
  hostOverride ? tsString(hostOverride) : 'null'
} as string | null;
`;

fs.writeFileSync(outPath, contents);
console.log(
  `[donna-app] env synced → voice target: ${target}` +
    (hostOverride ? `, host: ${hostOverride}` : '') +
    (wsOverride ? `, ws: ${wsOverride}` : ''),
);
