#!/usr/bin/env node
/**
 * Reads repo-root .env and writes src/env.generated.ts for the React Native app.
 * Auto-detects the dev Mac's Bonjour hostname (stable when DHCP changes IPs).
 * Run automatically via prestart / preios / preandroid.
 */
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(appRoot, '..');
const envPath = path.join(repoRoot, '.env');
const outPath = path.join(appRoot, 'src', 'env.generated.ts');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const vars = {};
  for (const line of fs.readFileSync(filePath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

function tsString(value) {
  return JSON.stringify(value);
}

/**
 * Prefer Bonjour hostname (.local) so the app survives DHCP IP changes.
 * Falls back to the current LAN IP only if hostname detection fails.
 */
function detectDevHost() {
  try {
    const name = execSync('scutil --get LocalHostName', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (name) {
      return `${name}.local`;
    }
  } catch {
    // not macOS or scutil unavailable
  }

  try {
    const ip = execSync('ipconfig getifaddr en0', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (ip) {
      return ip;
    }
  } catch {
    // en0 may be offline
  }

  try {
    for (const nets of Object.values(os.networkInterfaces())) {
      for (const net of nets ?? []) {
        if (net.family === 'IPv4' && !net.internal) {
          return net.address;
        }
      }
    }
  } catch {
    // sandbox or restricted environment
  }

  return null;
}

const env = parseEnvFile(envPath);
const target = env.DONNA_VOICE_TARGET === 'production' ? 'production' : 'local';
const wsOverride = env.DONNA_VOICE_WS_URL?.trim() || null;
const devHost = target === 'local' ? detectDevHost() : null;

const contents = `// AUTO-GENERATED by scripts/sync-env.mjs — do not edit
// Re-run: npm start (or: node scripts/sync-env.mjs)

export const ENV_VOICE_TARGET = ${tsString(target)} as 'local' | 'production';
export const ENV_VOICE_WS_URL_OVERRIDE = ${
  wsOverride ? tsString(wsOverride) : 'null'
} as string | null;
export const ENV_VOICE_DEV_HOST = ${
  devHost ? tsString(devHost) : 'null'
} as string | null;
`;

fs.writeFileSync(outPath, contents);
console.log(
  `[donna-app] env synced → voice target: ${target}` +
    (devHost ? `, dev host: ${devHost}` : '') +
    (wsOverride ? `, ws: ${wsOverride}` : ''),
);
