// AUTO-GENERATED by scripts/sync-env.mjs — do not edit
// Re-run: npm start (or: node scripts/sync-env.mjs)

export const ENV_VOICE_TARGET = "local" as 'local' | 'production';
export const ENV_VOICE_WS_URL_OVERRIDE = null as string | null;
export const ENV_VOICE_DEV_HOST = "Kishans-MacBook-Pro-470.local" as string | null;
export const ENV_PRIVACY_POLICY_URL = "https://donna-web.vercel.app/privacy";
