// AUTO-GENERATED by scripts/sync-env.mjs — do not edit
// Re-run: npm start (or: node scripts/sync-env.mjs)

export const ENV_VOICE_TARGET = "local" as 'local' | 'production';
export const ENV_VOICE_WS_URL_OVERRIDE = null as string | null;
export const ENV_VOICE_DEV_HOST = null as string | null;
